Changes to SmartIntake, need to be confirmed and pushed to master
FRC830/2024Robot pull request #18
Opened 2024-02-19 01:10 UTC by JoeyBrar

-Siddhant

2024-02-19 01:15 UTC, JoeyBrar commented
@Harsh-Sinha Please review.  - Nick & Sid

2024-02-20 01:52 UTC, Harsh-Sinha requested changes
Overall, good job. A couple bug fixes to be made.

2024-02-20 01:52 UTC, Harsh-Sinha commented on src/main/cpp/subsystems/SmartIntake.cpp
> +            m_SmartIntakeFlag = false;
This should not be in the default case. Make an explicit case for switching over to false. We use the default case to do nothing

2024-02-20 01:52 UTC, Harsh-Sinha commented on src/main/cpp/subsystems/SmartIntake.cpp
> +        case 2:
this should start at case 0.

2024-02-20 01:52 UTC, Harsh-Sinha commented on src/main/cpp/subsystems/SmartIntake.cpp
> +            input.intakeInput.runIntakeIn = true;
checking if the laser hit should be in the true case. The if statement should conditionally transfer to the false case

2024-02-20 01:52 UTC, Harsh-Sinha commented on src/main/cpp/subsystems/SmartIntake.cpp
> +            m_SmartOutTakeFlag = false;
see associated comment for intake

2024-02-20 01:52 UTC, Harsh-Sinha commented on src/main/cpp/subsystems/SmartIntake.cpp
> +        case 2:
see associated comment for intake

2024-02-20 01:52 UTC, Harsh-Sinha commented on src/main/cpp/subsystems/SmartIntake.cpp
> +            input.intakeInput.runIntakeOut = true;
see associated comment for intake

2024-02-21 00:04 UTC, merged